


const { config } = require("../config");
const { TooManyRequestsError, BadRequestError } = require("./errorTypes");
const otpgenerator = require("otp-generator");
const RedisClient = require("../config/redis");
const crypto = require("crypto");

const redis = RedisClient.getInstance();

const OTP_TTL = parseInt(config.OTP_TTL) || 300;
const OTP_MAX_PER_HOUR = parseInt(config.OTP_MAX_PER_HOUR) || 5;
const HMAC_SECRET = config.HMAC_SECRET || "default_secret_key";

// 🔐 HMAC generator
function hmacFor(email, otp) {
    return crypto
        .createHmac("sha256", HMAC_SECRET)
        .update(`${email}:${otp}`)
        .digest("hex");
}

exports.generateAndStoreOtp = async (meta) => {

    console.log("📨 Generating OTP for:", meta?.email);

    if (!meta?.email) {
        throw new Error("Email is required for OTP generation");
    }

    const rateKey = `otp:rate:${meta.email}`;

    const sendCount = parseInt(await redis.get(rateKey)) || 0;
    console.log("🔁 OTP sent count:", sendCount);

    if (sendCount >= OTP_MAX_PER_HOUR) {
        throw new TooManyRequestsError(
            "Too many OTP requests. Please try again later."
        );
    }

    const otp = otpgenerator.generate(6, {
        upperCase: false,
        specialChars: false,
        alphabets: false,
    });

      console.log("this is opt generated by opt",otp)

    const otpSessionId = crypto.randomUUID();
    const expiresAt = new Date(Date.now() + OTP_TTL * 1000);
    const hashedOtp = hmacFor(meta.email, otp);

    console.log("🔐 OTP Generated:", otp);
    console.log("🆔 OTP Session ID:", otpSessionId);

    await redis.setex(
        `otp:session:${otpSessionId}`,
        OTP_TTL,
        JSON.stringify({
            email: meta.email,
            otp: hashedOtp,
            expiresAt: expiresAt.toISOString(),
            meta,
        })
    );

    await redis.incr(rateKey);
    await redis.expire(rateKey, 3600);

    console.log("✅ OTP stored in Redis successfully");

    return { otp, otpSessionId };
};

exports.verifyOTPHased = async (otpSessionId, otp) => {

    // console.log("🔎 Verifying OTP for session:", otpSessionId);
    //  console.log(" Verifying OTP session :", otpSessionId, "otp value",otp );
    if (!otpSessionId || !otp) {
        throw new BadRequestError("OTP session ID and OTP are required");
    }

     console.log(" Verifying OTP session :", otpSessionId, "otp value",otp );

    const sessionKey = `otp:session:${otpSessionId}`;
    const sessionData = await redis.get(sessionKey);

    if (!sessionData) {
        console.log("❌ No session found in Redis");
        throw new BadRequestError("Invalid OTP session ID");
    }

    const parsedSessionData = JSON.parse(sessionData);

    // Expiry check
    if (new Date(parsedSessionData.expiresAt) < new Date()) {
        console.log("⏳ OTP expired");
        throw new BadRequestError("OTP has expired");
    }

    const attemptKey = `otp:attempts:${otpSessionId}`;
    let attempts = parseInt(await redis.get(attemptKey)) || 0;

    console.log("🔁 Current verification attempts:", attempts);

    if (attempts >= 5) {
        throw new TooManyRequestsError(
            "Too many OTP verification attempts. Please try again later."
        );
    }

    const expectedHash = hmacFor(parsedSessionData.email, otp);

    let otpMatches = false;

    if (
        expectedHash.length === parsedSessionData.otp.length
    ) {
        try {
            otpMatches = crypto.timingSafeEqual(
                Buffer.from(expectedHash, "hex"),
                Buffer.from(parsedSessionData.otp, "hex")
            );
        } catch (err) {
            otpMatches = false;
        }
    }

    if (otpMatches) {
        console.log("✅ OTP verified successfully");

        await redis.del(sessionKey);
        await redis.del(attemptKey);
        await redis.del(`otp:rate:${parsedSessionData.email}`);

        console.log("🧹 Redis cleanup completed");

        return parsedSessionData.meta;
    } else {
        attempts++;

        await redis.setex(attemptKey, OTP_TTL, attempts);

        console.log("❌ Invalid OTP attempt:", attempts);

        throw new BadRequestError("Invalid OTP");
    }
};
